In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("SRN-CSRD_report_archive.xlsx", sheet_name="csrd")

In [3]:
df

,verified,company,isin,country,publication date,claim full \nCSRD,auditor,start PDF,end PDF,pages PDF,link,SASB industry \n(SICS® Industries)
0,yes,Netcompany,DK0060952919,Denmark,2025-01-29,True,EY,62.0,154.0,92.0,https://netcompany.com/investor/annual-report/,Internet Media & Services
1,yes,Tryg,DK0060636678,Denmark,2025-01-23,True,PwC,53.0,131.0,78.0,https://tryg.com/sites/tryg.com/files/2025-01/...,Insurance
2,yes,DSV,DK0060079531,Denmark,2025-02-04,True,PwC,42.0,84.0,42.0,https://investor.dsv.com/static-files/d34d3dfc...,Air Freight & Logistics
3,yes,Lundbeck,DK0061804697,Denmark,2025-02-04,True,PwC,59.0,144.0,85.0,https://www.lundbeck.com/content/dam/lundbeck-...,Biotechnology & Pharmaceuticals
4,yes,Vestas,DK0061539921,Denmark,2025-02-05,True,Deloitte,51.0,132.0,81.0,https://www.vestas.com/content/dam/vestas-com/...,Wind Technology & Project Developers
...,...,...,...,...,...,...,...,...,...,...,...,...
2068,NaN,NaN,NaN,NaN,NaT,False,NaN,NaN,NaN,NaN,NaN,NaN
2069,NaN,NaN,NaN,NaN,NaT,False,NaN,NaN,NaN,NaN,NaN,NaN
2070,NaN,NaN,NaN,NaN,NaT,False,NaN,NaN,NaN,NaN,NaN,NaN
2071,NaN,NaN,NaN,NaN,NaT,False,NaN,NaN,NaN,NaN,NaN,NaN
2072,NaN,NaN,NaN,NaN,NaT,False,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
industry_lookup = pd.read_excel("SRN-CSRD_report_archive.xlsx", sheet_name="industries")

In [9]:
csrd_url = "https://docs.google.com/spreadsheets/d/1Nlyf8Yz_9Fst8rEmQc2IMc-DWLF1fpmBTB7n4FlZwxs/export?format=csv&gid=0"
industry_url = "https://docs.google.com/spreadsheets/d/1Nlyf8Yz_9Fst8rEmQc2IMc-DWLF1fpmBTB7n4FlZwxs/export?format=csv&gid=1695573594"

pd.read_csv(csrd_url)

,Find our new interactive dashboard here,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,verified,company,isin,country,publication date,claim full \nCSRD,auditor,start PDF,end PDF,pages PDF,link,SASB industry \n(SICS® Industries)
1,yes,Netcompany,DK0060952919,Denmark,29/01/2025,TRUE,EY,62,154,92,https://netcompany.com/investor/annual-report/,Internet Media & Services
2,yes,Tryg,DK0060636678,Denmark,23/01/2025,TRUE,PwC,53,131,78,https://tryg.com/sites/tryg.com/files/2025-01/...,Insurance
3,yes,DSV,DK0060079531,Denmark,04/02/2025,TRUE,PwC,42,84,42,https://investor.dsv.com/static-files/d34d3dfc...,Air Freight & Logistics
4,yes,Lundbeck,DK0061804697,Denmark,04/02/2025,TRUE,PwC,59,144,85,https://www.lundbeck.com/content/dam/lundbeck-...,Biotechnology & Pharmaceuticals
...,...,...,...,...,...,...,...,...,...,...,...,...
2062,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN
2063,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN
2064,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN
2065,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN
2066,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pd.read_csv( "https://docs.google.com/spreadsheets/d/1Nlyf8Yz_9Fst8rEmQc2IMc-DWLF1fpmBTB7n4FlZwxs/edit?gid=218767986#gid=218767986")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Sustainability Reporting Navigator
2,NaN,NaN,NaN,CSRD Report Archive
3,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,Welcome to the SRN CSRD Report Archive. On the...
5,NaN,NaN,NaN,to learn about and share annual reports prepar...
6,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,"In the csrd sheet, you find a list of CSRD-com..."
8,NaN,NaN,NaN,we will approve them and mark those in gray. P...
9,NaN,NaN,NaN,"but do not make any audit, verification, or as..."
10,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,"In the non-csrd (other) reports sheet, feel fr..."
12,NaN,NaN,NaN,"From time to time, we move non-compliant repor..."
13,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,Join our newsletter to stay up to date for new...
15,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,https://sustainabilityreportingnavigator.com/